[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
    " シンボルカラムを表示したままにする
    let g:ale_sign_column_always = 1
    " エラー行に表示するマーク
    let g:ale_sign_error = '⨉'
    let g:ale_sign_warning = '⚠'
'''

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'kovisoft/slimv'
hook_add = '''
    let g:slimv_swank_cmd = '! screen -d -m -t REPL-SBCL sbcl --load ~/.cache/dein/repos/github.com/kovisoft/slimv/slime/start-swank.lisp'
nmap <Leader>l [LISP]
nnoremap [LISP] :<BS>
nmap [LISP]e [LISP-EVAL]
nnoremap [LISP]c :call SlimvConnectServer()<CR>
nnoremap [LISP-EVAL] :<BS>
nnoremap [LISP-EVAL]d :call SlimvEvalDefun()<CR>
nnoremap [LISP-EVAL]b :call SlimvEvalBuffer()<CR>
'''

#[[plugins]]
#repo = 'jdkanani/vim-material-theme'
#hook_add = '''
#"set t_Co=256
#"set termguicolors
#"set background=dark
#"colorscheme material-theme
#'''
#[[plugins]]
#repo = 'chriskempson/base16-vim'
#hook_add = '''
#if filereadable(expand("~/.vimrc_background"))
#  let base16colorspace=256
#  source ~/.vimrc_background
#endif
#colorscheme base16-monokai
#'''

[[plugins]]
repo = 'RRethy/nvim-base16'
hook_add = '''
colorscheme base16-monokai
'''
