[theme]
theme = "plain"

[[block]]
block = "net"
format = " $ip (^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K)) "

[[block]]
block = "battery"
format = " $icon $percentage.eng(w:5) {($time)|} "
full_format =  " $icon $percentage.eng(w:5) {($time)|} "
charging_format =  " $icon $percentage.eng(w:5) {($time)|} "
empty_format =  " $icon $percentage.eng(w:5) {($time)|} "
not_charging_format =  " $icon $percentage.eng(w:5) {($time)|} "
missing_format = ""
interval = 1

[[block]]
block = "disk_space"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "custom"
command = "bluetoothctl info | grep -oP '(?<=Battery Percentage:).*' | grep -oP '(?<=\\()\\d+' | sed -e 's/$/%/' | tr '\n' , | sed  -e 's/,$//'"
interval = 60
hide_when_empty = true
format = " BL: $text "

[[block]]
block = "memory"
interval = 1
format = " $mem_used.eng(prefix:Mi,w:4)/$mem_total.eng(prefix:Mi,w:4)($mem_used_percents.eng(w:2)) "

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%Y/%m/%d %H:%M:%S') "
interval = 1
