#include<gio/gio.h>
#undef g_object_ref
#undef g_object_ref_sink
typedef   unsigned long   gsize ;
typedef   char   gchar ;
typedef   int   gint ;
typedef   const   void  *  gconstpointer ;
extern   gboolean   g_variant_type_string_is_valid ( const   gchar  *  type_string );
extern   gboolean   g_variant_type_string_scan ( const   gchar  *  string ,  const   gchar  *  limit ,  const   gchar  * *  endptr );
extern   void   g_variant_type_free ( GVariantType  *  type );
extern   GVariantType  *  g_variant_type_copy ( const   GVariantType  *  type );
extern   GVariantType  *  g_variant_type_new ( const   gchar  *  type_string );
extern   gsize   g_variant_type_get_string_length ( const   GVariantType  *  type );
extern   const   gchar  *  g_variant_type_peek_string ( const   GVariantType  *  type );
extern   gchar  *  g_variant_type_dup_string ( const   GVariantType  *  type );
extern   gboolean   g_variant_type_is_definite ( const   GVariantType  *  type );
extern   gboolean   g_variant_type_is_container ( const   GVariantType  *  type );
extern   gboolean   g_variant_type_is_basic ( const   GVariantType  *  type );
extern   gboolean   g_variant_type_is_maybe ( const   GVariantType  *  type );
extern   gboolean   g_variant_type_is_array ( const   GVariantType  *  type );
extern   gboolean   g_variant_type_is_tuple ( const   GVariantType  *  type );
extern   gboolean   g_variant_type_is_dict_entry ( const   GVariantType  *  type );
extern   gboolean   g_variant_type_is_variant ( const   GVariantType  *  type );
extern   guint   g_variant_type_hash ( gconstpointer   type );
extern   gboolean   g_variant_type_equal ( gconstpointer   type1 ,  gconstpointer   type2 );
extern   gboolean   g_variant_type_is_subtype_of ( const   GVariantType  *  type ,  const   GVariantType  *  supertype );
extern   const   GVariantType  *  g_variant_type_element ( const   GVariantType  *  type );
extern   const   GVariantType  *  g_variant_type_first ( const   GVariantType  *  type );
extern   const   GVariantType  *  g_variant_type_next ( const   GVariantType  *  type );
extern   gsize   g_variant_type_n_items ( const   GVariantType  *  type );
extern   const   GVariantType  *  g_variant_type_key ( const   GVariantType  *  type );
extern   const   GVariantType  *  g_variant_type_value ( const   GVariantType  *  type );
extern   GVariantType  *  g_variant_type_new_array ( const   GVariantType  *  element );
extern   GVariantType  *  g_variant_type_new_maybe ( const   GVariantType  *  element );
extern   GVariantType  *  g_variant_type_new_tuple ( const   GVariantType  *  const  *  items ,  gint   length );
extern   GVariantType  *  g_variant_type_new_dict_entry ( const   GVariantType  *  key ,  const   GVariantType  *  value );
extern   const   GVariantType  *  g_variant_type_checked_ ( const   gchar  *  type_string );
extern   gsize   g_variant_type_string_get_depth_ ( const   gchar  *  type_string );
extern   void   g_variant_unref ( GVariant  *  value );
extern   GVariant  *  g_variant_ref ( GVariant  *  value );
extern   GVariant  *  g_variant_ref_sink ( GVariant  *  value );
extern   gboolean   g_variant_is_floating ( GVariant  *  value );
extern   GVariant  *  g_variant_take_ref ( GVariant  *  value );
extern   const   GVariantType  *  g_variant_get_type ( GVariant  *  value );
extern   const   gchar  *  g_variant_get_type_string ( GVariant  *  value );
extern   gboolean   g_variant_is_of_type ( GVariant  *  value ,  const   GVariantType  *  type );
extern   gboolean   g_variant_is_container ( GVariant  *  value );
extern   GVariantClass   g_variant_classify ( GVariant  *  value );
extern   GVariant  *  g_variant_new_boolean ( gboolean   value );
extern   GVariant  *  g_variant_new_byte ( guint8   value );
extern   GVariant  *  g_variant_new_int16 ( gint16   value );
extern   GVariant  *  g_variant_new_uint16 ( guint16   value );
extern   GVariant  *  g_variant_new_int32 ( gint32   value );
extern   GVariant  *  g_variant_new_uint32 ( guint32   value );
extern   GVariant  *  g_variant_new_int64 ( gint64   value );
extern   GVariant  *  g_variant_new_uint64 ( guint64   value );
extern   GVariant  *  g_variant_new_handle ( gint32   value );
extern   GVariant  *  g_variant_new_double ( gdouble   value );
extern   GVariant  *  g_variant_new_string ( const   gchar  *  string );
extern   GVariant  *  g_variant_new_take_string ( gchar  *  string );
extern   GVariant  *  g_variant_new_printf ( const   gchar  *  format_string , ...);
extern   GVariant  *  g_variant_new_object_path ( const   gchar  *  object_path );
extern   gboolean   g_variant_is_object_path ( const   gchar  *  string );
extern   GVariant  *  g_variant_new_signature ( const   gchar  *  signature );
extern   gboolean   g_variant_is_signature ( const   gchar  *  string );
extern   GVariant  *  g_variant_new_variant ( GVariant  *  value );
extern   GVariant  *  g_variant_new_strv ( const   gchar  *  const  *  strv ,  gssize   length );
extern   GVariant  *  g_variant_new_objv ( const   gchar  *  const  *  strv ,  gssize   length );
extern   GVariant  *  g_variant_new_bytestring ( const   gchar  *  string );
extern   GVariant  *  g_variant_new_bytestring_array ( const   gchar  *  const  *  strv ,  gssize   length );
extern   GVariant  *  g_variant_new_fixed_array ( const   GVariantType  *  element_type ,  gconstpointer   elements ,  gsize   n_elements ,  gsize   element_size );
extern   gboolean   g_variant_get_boolean ( GVariant  *  value );
extern   guint8   g_variant_get_byte ( GVariant  *  value );
extern   gint16   g_variant_get_int16 ( GVariant  *  value );
extern   guint16   g_variant_get_uint16 ( GVariant  *  value );
extern   gint32   g_variant_get_int32 ( GVariant  *  value );
extern   guint32   g_variant_get_uint32 ( GVariant  *  value );
extern   gint64   g_variant_get_int64 ( GVariant  *  value );
extern   guint64   g_variant_get_uint64 ( GVariant  *  value );
extern   gint32   g_variant_get_handle ( GVariant  *  value );
extern   gdouble   g_variant_get_double ( GVariant  *  value );
extern   GVariant  *  g_variant_get_variant ( GVariant  *  value );
extern   const   gchar  *  g_variant_get_string ( GVariant  *  value ,  gsize  *  length );
extern   gchar  *  g_variant_dup_string ( GVariant  *  value ,  gsize  *  length );
extern   const   gchar  * *  g_variant_get_strv ( GVariant  *  value ,  gsize  *  length );
extern   gchar  * *  g_variant_dup_strv ( GVariant  *  value ,  gsize  *  length );
extern   const   gchar  * *  g_variant_get_objv ( GVariant  *  value ,  gsize  *  length );
extern   gchar  * *  g_variant_dup_objv ( GVariant  *  value ,  gsize  *  length );
extern   const   gchar  *  g_variant_get_bytestring ( GVariant  *  value );
extern   gchar  *  g_variant_dup_bytestring ( GVariant  *  value ,  gsize  *  length );
extern   const   gchar  * *  g_variant_get_bytestring_array ( GVariant  *  value ,  gsize  *  length );
extern   gchar  * *  g_variant_dup_bytestring_array ( GVariant  *  value ,  gsize  *  length );
extern   GVariant  *  g_variant_new_maybe ( const   GVariantType  *  child_type ,  GVariant  *  child );
extern   GVariant  *  g_variant_new_array ( const   GVariantType  *  child_type ,  GVariant  *  const  *  children ,  gsize   n_children );
extern   GVariant  *  g_variant_new_tuple ( GVariant  *  const  *  children ,  gsize   n_children );
extern   GVariant  *  g_variant_new_dict_entry ( GVariant  *  key ,  GVariant  *  value );
extern   GVariant  *  g_variant_get_maybe ( GVariant  *  value );
extern   gsize   g_variant_n_children ( GVariant  *  value );
extern   void   g_variant_get_child ( GVariant  *  value ,  gsize   index_ ,  const   gchar  *  format_string , ...);
extern   GVariant  *  g_variant_get_child_value ( GVariant  *  value ,  gsize   index_ );
extern   gboolean   g_variant_lookup ( GVariant  *  dictionary ,  const   gchar  *  key ,  const   gchar  *  format_string , ...);
extern   GVariant  *  g_variant_lookup_value ( GVariant  *  dictionary ,  const   gchar  *  key ,  const   GVariantType  *  expected_type );
extern   gconstpointer   g_variant_get_fixed_array ( GVariant  *  value ,  gsize  *  n_elements ,  gsize   element_size );
extern   gsize   g_variant_get_size ( GVariant  *  value );
extern   gconstpointer   g_variant_get_data ( GVariant  *  value );
extern   GBytes  *  g_variant_get_data_as_bytes ( GVariant  *  value );
extern   void   g_variant_store ( GVariant  *  value ,  gpointer   data );
extern   gchar  *  g_variant_print ( GVariant  *  value ,  gboolean   type_annotate );
extern   GString  *  g_variant_print_string ( GVariant  *  value ,  GString  *  string ,  gboolean   type_annotate );
extern   guint   g_variant_hash ( gconstpointer   value );
extern   gboolean   g_variant_equal ( gconstpointer   one ,  gconstpointer   two );
extern   GVariant  *  g_variant_get_normal_form ( GVariant  *  value );
extern   gboolean   g_variant_is_normal_form ( GVariant  *  value );
extern   GVariant  *  g_variant_byteswap ( GVariant  *  value );
extern   GVariant  *  g_variant_new_from_bytes ( const   GVariantType  *  type ,  GBytes  *  bytes ,  gboolean   trusted );
extern   GVariant  *  g_variant_new_from_data ( const   GVariantType  *  type ,  gconstpointer   data ,  gsize   size ,  gboolean   trusted ,  GDestroyNotify   notify ,  gpointer   user_data );
extern   GVariantIter  *  g_variant_iter_new ( GVariant  *  value );
extern   gsize   g_variant_iter_init ( GVariantIter  *  iter ,  GVariant  *  value );
extern   GVariantIter  *  g_variant_iter_copy ( GVariantIter  *  iter );
extern   gsize   g_variant_iter_n_children ( GVariantIter  *  iter );
extern   void   g_variant_iter_free ( GVariantIter  *  iter );
extern   GVariant  *  g_variant_iter_next_value ( GVariantIter  *  iter );
extern   gboolean   g_variant_iter_next ( GVariantIter  *  iter ,  const   gchar  *  format_string , ...);
extern   gboolean   g_variant_iter_loop ( GVariantIter  *  iter ,  const   gchar  *  format_string , ...);
extern   GQuark   g_variant_parser_get_error_quark ();
extern   GQuark   g_variant_parse_error_quark ();
extern   GVariantBuilder  *  g_variant_builder_new ( const   GVariantType  *  type );
extern   void   g_variant_builder_unref ( GVariantBuilder  *  builder );
extern   GVariantBuilder  *  g_variant_builder_ref ( GVariantBuilder  *  builder );
extern   void   g_variant_builder_init ( GVariantBuilder  *  builder ,  const   GVariantType  *  type );
extern   GVariant  *  g_variant_builder_end ( GVariantBuilder  *  builder );
extern   void   g_variant_builder_clear ( GVariantBuilder  *  builder );
extern   void   g_variant_builder_open ( GVariantBuilder  *  builder ,  const   GVariantType  *  type );
extern   void   g_variant_builder_close ( GVariantBuilder  *  builder );
extern   void   g_variant_builder_add_value ( GVariantBuilder  *  builder ,  GVariant  *  value );
extern   void   g_variant_builder_add ( GVariantBuilder  *  builder ,  const   gchar  *  format_string , ...);
extern   void   g_variant_builder_add_parsed ( GVariantBuilder  *  builder ,  const   gchar  *  format , ...);
extern   GVariant  *  g_variant_new ( const   gchar  *  format_string , ...);
extern   void   g_variant_get ( GVariant  *  value ,  const   gchar  *  format_string , ...);
extern   GVariant  *  g_variant_new_va ( const   gchar  *  format_string ,  const   gchar  * *  endptr ,  va_list  *  app );
extern   void   g_variant_get_va ( GVariant  *  value ,  const   gchar  *  format_string ,  const   gchar  * *  endptr ,  va_list  *  app );
extern   gboolean   g_variant_check_format_string ( GVariant  *  value ,  const   gchar  *  format_string ,  gboolean   copy_only );
extern   GVariant  *  g_variant_parse ( const   GVariantType  *  type ,  const   gchar  *  text ,  const   gchar  *  limit ,  const   gchar  * *  endptr ,  GError  * *  error );
extern   GVariant  *  g_variant_new_parsed ( const   gchar  *  format , ...);
extern   GVariant  *  g_variant_new_parsed_va ( const   gchar  *  format ,  va_list  *  app );
extern   gchar  *  g_variant_parse_error_print_context ( GError  *  error ,  const   gchar  *  source_str );
extern   gint   g_variant_compare ( gconstpointer   one ,  gconstpointer   two );
extern   GVariantDict  *  g_variant_dict_new ( GVariant  *  from_asv );
extern   void   g_variant_dict_init ( GVariantDict  *  dict ,  GVariant  *  from_asv );
extern   gboolean   g_variant_dict_lookup ( GVariantDict  *  dict ,  const   gchar  *  key ,  const   gchar  *  format_string , ...);
extern   GVariant  *  g_variant_dict_lookup_value ( GVariantDict  *  dict ,  const   gchar  *  key ,  const   GVariantType  *  expected_type );
extern   gboolean   g_variant_dict_contains ( GVariantDict  *  dict ,  const   gchar  *  key );
extern   void   g_variant_dict_insert ( GVariantDict  *  dict ,  const   gchar  *  key ,  const   gchar  *  format_string , ...);
extern   void   g_variant_dict_insert_value ( GVariantDict  *  dict ,  const   gchar  *  key ,  GVariant  *  value );
extern   gboolean   g_variant_dict_remove ( GVariantDict  *  dict ,  const   gchar  *  key );
extern   void   g_variant_dict_clear ( GVariantDict  *  dict );
extern   GVariant  *  g_variant_dict_end ( GVariantDict  *  dict );
extern   GVariantDict  *  g_variant_dict_ref ( GVariantDict  *  dict );
extern   void   g_variant_dict_unref ( GVariantDict  *  dict );
extern   GType   g_variant_type_get_gtype ();
extern   GType   g_variant_builder_get_type ();
extern   GType   g_variant_dict_get_type ();
extern   GType   g_variant_get_gtype ();
extern   void   g_object_class_install_property ( GObjectClass  *  oclass ,  guint   property_id ,  GParamSpec  *  pspec );
extern   GParamSpec  *  g_object_class_find_property ( GObjectClass  *  oclass ,  const   gchar  *  property_name );
extern   GParamSpec  * *  g_object_class_list_properties ( GObjectClass  *  oclass ,  guint  *  n_properties );
extern   void   g_object_class_override_property ( GObjectClass  *  oclass ,  guint   property_id ,  const   gchar  *  name );
extern   void   g_object_class_install_properties ( GObjectClass  *  oclass ,  guint   n_pspecs ,  GParamSpec  * *  pspecs );
extern   void   g_object_interface_install_property ( gpointer   g_iface ,  GParamSpec  *  pspec );
extern   GParamSpec  *  g_object_interface_find_property ( gpointer   g_iface ,  const   gchar  *  property_name );
extern   GParamSpec  * *  g_object_interface_list_properties ( gpointer   g_iface ,  guint  *  n_properties_p );
extern   GType   g_object_get_type ();
extern   gpointer   g_object_new ( GType   object_type ,  const   gchar  *  first_property_name , ...);
extern   GObject  *  g_object_new_with_properties ( GType   object_type ,  guint   n_properties ,  const   char  *  names [],  const   GValue   values []);
extern   gpointer   g_object_newv ( GType   object_type ,  guint   n_parameters ,  GParameter  *  parameters );
extern   GObject  *  g_object_new_valist ( GType   object_type ,  const   gchar  *  first_property_name ,  va_list   var_args );
extern   void   g_object_set ( gpointer   object ,  const   gchar  *  first_property_name , ...);
extern   void   g_object_get ( gpointer   object ,  const   gchar  *  first_property_name , ...);
extern   gpointer   g_object_connect ( gpointer   object ,  const   gchar  *  signal_spec , ...);
extern   void   g_object_disconnect ( gpointer   object ,  const   gchar  *  signal_spec , ...);
extern   void   g_object_setv ( GObject  *  object ,  guint   n_properties ,  const   gchar  *  names [],  const   GValue   values []);
extern   void   g_object_set_valist ( GObject  *  object ,  const   gchar  *  first_property_name ,  va_list   var_args );
extern   void   g_object_getv ( GObject  *  object ,  guint   n_properties ,  const   gchar  *  names [],  GValue   values []);
extern   void   g_object_get_valist ( GObject  *  object ,  const   gchar  *  first_property_name ,  va_list   var_args );
extern   void   g_object_set_property ( GObject  *  object ,  const   gchar  *  property_name ,  const   GValue  *  value );
extern   void   g_object_get_property ( GObject  *  object ,  const   gchar  *  property_name ,  GValue  *  value );
extern   void   g_object_freeze_notify ( GObject  *  object );
extern   void   g_object_notify ( GObject  *  object ,  const   gchar  *  property_name );
extern   void   g_object_notify_by_pspec ( GObject  *  object ,  GParamSpec  *  pspec );
extern   void   g_object_thaw_notify ( GObject  *  object );
extern   gboolean   g_object_is_floating ( gpointer   object );
extern   gpointer   g_object_ref_sink ( gpointer   object );
extern   gpointer   g_object_take_ref ( gpointer   object );
extern   gpointer   g_object_ref ( gpointer   object );
extern   void   g_object_unref ( gpointer   object );
extern   void   g_object_weak_ref ( GObject  *  object ,  GWeakNotify   notify ,  gpointer   data );
extern   void   g_object_weak_unref ( GObject  *  object ,  GWeakNotify   notify ,  gpointer   data );
extern   void   g_object_add_weak_pointer ( GObject  *  object ,  gpointer  *  weak_pointer_location );
extern   void   g_object_remove_weak_pointer ( GObject  *  object ,  gpointer  *  weak_pointer_location );
extern   void   g_object_add_toggle_ref ( GObject  *  object ,  GToggleNotify   notify ,  gpointer   data );
extern   void   g_object_remove_toggle_ref ( GObject  *  object ,  GToggleNotify   notify ,  gpointer   data );
extern   gpointer   g_object_get_qdata ( GObject  *  object ,  GQuark   quark );
extern   void   g_object_set_qdata ( GObject  *  object ,  GQuark   quark ,  gpointer   data );
extern   void   g_object_set_qdata_full ( GObject  *  object ,  GQuark   quark ,  gpointer   data ,  GDestroyNotify   destroy );
extern   gpointer   g_object_steal_qdata ( GObject  *  object ,  GQuark   quark );
extern   gpointer   g_object_dup_qdata ( GObject  *  object ,  GQuark   quark ,  GDuplicateFunc   dup_func ,  gpointer   user_data );
extern   gboolean   g_object_replace_qdata ( GObject  *  object ,  GQuark   quark ,  gpointer   oldval ,  gpointer   newval ,  GDestroyNotify   destroy ,  GDestroyNotify  *  old_destroy );
extern   gpointer   g_object_get_data ( GObject  *  object ,  const   gchar  *  key );
extern   void   g_object_set_data ( GObject  *  object ,  const   gchar  *  key ,  gpointer   data );
extern   void   g_object_set_data_full ( GObject  *  object ,  const   gchar  *  key ,  gpointer   data ,  GDestroyNotify   destroy );
extern   gpointer   g_object_steal_data ( GObject  *  object ,  const   gchar  *  key );
extern   gpointer   g_object_dup_data ( GObject  *  object ,  const   gchar  *  key ,  GDuplicateFunc   dup_func ,  gpointer   user_data );
extern   gboolean   g_object_replace_data ( GObject  *  object ,  const   gchar  *  key ,  gpointer   oldval ,  gpointer   newval ,  GDestroyNotify   destroy ,  GDestroyNotify  *  old_destroy );
extern   void   g_object_watch_closure ( GObject  *  object ,  GClosure  *  closure );
extern   void   g_object_force_floating ( GObject  *  object );
extern   void   g_object_run_dispose ( GObject  *  object );
extern   gsize   g_object_compat_control ( gsize   what ,  gpointer   data );
extern   GBinding  *  g_object_bind_property ( gpointer   source ,  const   gchar  *  source_property ,  gpointer   target ,  const   gchar  *  target_property ,  GBindingFlags   flags );
extern   GBinding  *  g_object_bind_property_full ( gpointer   source ,  const   gchar  *  source_property ,  gpointer   target ,  const   gchar  *  target_property ,  GBindingFlags   flags ,  GBindingTransformFunc   transform_to ,  GBindingTransformFunc   transform_from ,  gpointer   user_data ,  GDestroyNotify   notify );
extern   GBinding  *  g_object_bind_property_with_closures ( gpointer   source ,  const   gchar  *  source_property ,  gpointer   target ,  const   gchar  *  target_property ,  GBindingFlags   flags ,  GClosure  *  transform_to ,  GClosure  *  transform_from );
extern   guint   g_dbus_connection_export_action_group ( GDBusConnection  *  connection ,  const   gchar  *  object_path ,  GActionGroup  *  action_group ,  GError  * *  error );
extern   void   g_dbus_connection_unexport_action_group ( GDBusConnection  *  connection ,  guint   export_id );
extern   GType   g_dbus_action_group_get_type ();
extern   GDBusActionGroup  *  g_dbus_action_group_get ( GDBusConnection  *  connection ,  const   gchar  *  bus_name ,  const   gchar  *  object_path );
extern   gchar  *  g_dbus_address_escape_value ( const   gchar  *  string );
extern   gboolean   g_dbus_is_address ( const   gchar  *  string );
extern   gboolean   g_dbus_is_supported_address ( const   gchar  *  string ,  GError  * *  error );
extern   void   g_dbus_address_get_stream ( const   gchar  *  address ,  GCancellable  *  cancellable ,  GAsyncReadyCallback   callback ,  gpointer   user_data );
extern   GIOStream  *  g_dbus_address_get_stream_finish ( GAsyncResult  *  res ,  gchar  * *  out_guid ,  GError  * *  error );
extern   GIOStream  *  g_dbus_address_get_stream_sync ( const   gchar  *  address ,  gchar  * *  out_guid ,  GCancellable  *  cancellable ,  GError  * *  error );
extern   gchar  *  g_dbus_address_get_for_bus_sync ( GBusType   bus_type ,  GCancellable  *  cancellable ,  GError  * *  error );
extern   GType   g_dbus_auth_observer_get_type ();
extern   GDBusAuthObserver  *  g_dbus_auth_observer_new ();
extern   gboolean   g_dbus_auth_observer_authorize_authenticated_peer ( GDBusAuthObserver  *  observer ,  GIOStream  *  stream ,  GCredentials  *  credentials );
extern   gboolean   g_dbus_auth_observer_allow_mechanism ( GDBusAuthObserver  *  observer ,  const   gchar  *  mechanism );
extern   GType   g_dbus_connection_get_type ();
extern   void   g_dbus_connection_new ( GIOStream  *  stream ,  const   gchar  *  guid ,  GDBusConnectionFlags   flags ,  GDBusAuthObserver  *  observer ,  GCancellable  *  cancellable ,  GAsyncReadyCallback   callback ,  gpointer   user_data );
extern   GDBusConnection  *  g_dbus_connection_new_finish ( GAsyncResult  *  res ,  GError  * *  error );
extern   GDBusConnection  *  g_dbus_connection_new_sync ( GIOStream  *  stream ,  const   gchar  *  guid ,  GDBusConnectionFlags   flags ,  GDBusAuthObserver  *  observer ,  GCancellable  *  cancellable ,  GError  * *  error );
extern   void   g_dbus_connection_new_for_address ( const   gchar  *  address ,  GDBusConnectionFlags   flags ,  GDBusAuthObserver  *  observer ,  GCancellable  *  cancellable ,  GAsyncReadyCallback   callback ,  gpointer   user_data );
extern   GDBusConnection  *  g_dbus_connection_new_for_address_finish ( GAsyncResult  *  res ,  GError  * *  error );
extern   GDBusConnection  *  g_dbus_connection_new_for_address_sync ( const   gchar  *  address ,  GDBusConnectionFlags   flags ,  GDBusAuthObserver  *  observer ,  GCancellable  *  cancellable ,  GError  * *  error );
extern   void   g_dbus_connection_start_message_processing ( GDBusConnection  *  connection );
extern   gboolean   g_dbus_connection_is_closed ( GDBusConnection  *  connection );
extern   GIOStream  *  g_dbus_connection_get_stream ( GDBusConnection  *  connection );
extern   const   gchar  *  g_dbus_connection_get_guid ( GDBusConnection  *  connection );
extern   const   gchar  *  g_dbus_connection_get_unique_name ( GDBusConnection  *  connection );
extern   GCredentials  *  g_dbus_connection_get_peer_credentials ( GDBusConnection  *  connection );
extern   guint32   g_dbus_connection_get_last_serial ( GDBusConnection  *  connection );
extern   gboolean   g_dbus_connection_get_exit_on_close ( GDBusConnection  *  connection );
extern   void   g_dbus_connection_set_exit_on_close ( GDBusConnection  *  connection ,  gboolean   exit_on_close );
extern   GDBusCapabilityFlags   g_dbus_connection_get_capabilities ( GDBusConnection  *  connection );
extern   GDBusConnectionFlags   g_dbus_connection_get_flags ( GDBusConnection  *  connection );
extern   void   g_dbus_connection_close ( GDBusConnection  *  connection ,  GCancellable  *  cancellable ,  GAsyncReadyCallback   callback ,  gpointer   user_data );
extern   gboolean   g_dbus_connection_close_finish ( GDBusConnection  *  connection ,  GAsyncResult  *  res ,  GError  * *  error );
extern   gboolean   g_dbus_connection_close_sync ( GDBusConnection  *  connection ,  GCancellable  *  cancellable ,  GError  * *  error );
extern   void   g_dbus_connection_flush ( GDBusConnection  *  connection ,  GCancellable  *  cancellable ,  GAsyncReadyCallback   callback ,  gpointer   user_data );
extern   gboolean   g_dbus_connection_flush_finish ( GDBusConnection  *  connection ,  GAsyncResult  *  res ,  GError  * *  error );
extern   gboolean   g_dbus_connection_flush_sync ( GDBusConnection  *  connection ,  GCancellable  *  cancellable ,  GError  * *  error );
extern   gboolean   g_dbus_connection_send_message ( GDBusConnection  *  connection ,  GDBusMessage  *  message ,  GDBusSendMessageFlags   flags ,  volatile   guint32  *  out_serial ,  GError  * *  error );
extern   void   g_dbus_connection_send_message_with_reply ( GDBusConnection  *  connection ,  GDBusMessage  *  message ,  GDBusSendMessageFlags   flags ,  gint   timeout_msec ,  volatile   guint32  *  out_serial ,  GCancellable  *  cancellable ,  GAsyncReadyCallback   callback ,  gpointer   user_data );
extern   GDBusMessage  *  g_dbus_connection_send_message_with_reply_finish ( GDBusConnection  *  connection ,  GAsyncResult  *  res ,  GError  * *  error );
extern   GDBusMessage  *  g_dbus_connection_send_message_with_reply_sync ( GDBusConnection  *  connection ,  GDBusMessage  *  message ,  GDBusSendMessageFlags   flags ,  gint   timeout_msec ,  volatile   guint32  *  out_serial ,  GCancellable  *  cancellable ,  GError  * *  error );
extern   gboolean   g_dbus_connection_emit_signal ( GDBusConnection  *  connection ,  const   gchar  *  destination_bus_name ,  const   gchar  *  object_path ,  const   gchar  *  interface_name ,  const   gchar  *  signal_name ,  GVariant  *  parameters ,  GError  * *  error );
extern   void   g_dbus_connection_call ( GDBusConnection  *  connection ,  const   gchar  *  bus_name ,  const   gchar  *  object_path ,  const   gchar  *  interface_name ,  const   gchar  *  method_name ,  GVariant  *  parameters ,  const   GVariantType  *  reply_type ,  GDBusCallFlags   flags ,  gint   timeout_msec ,  GCancellable  *  cancellable ,  GAsyncReadyCallback   callback ,  gpointer   user_data );
extern   GVariant  *  g_dbus_connection_call_finish ( GDBusConnection  *  connection ,  GAsyncResult  *  res ,  GError  * *  error );
extern   GVariant  *  g_dbus_connection_call_sync ( GDBusConnection  *  connection ,  const   gchar  *  bus_name ,  const   gchar  *  object_path ,  const   gchar  *  interface_name ,  const   gchar  *  method_name ,  GVariant  *  parameters ,  const   GVariantType  *  reply_type ,  GDBusCallFlags   flags ,  gint   timeout_msec ,  GCancellable  *  cancellable ,  GError  * *  error );
extern   void   g_dbus_connection_call_with_unix_fd_list ( GDBusConnection  *  connection ,  const   gchar  *  bus_name ,  const   gchar  *  object_path ,  const   gchar  *  interface_name ,  const   gchar  *  method_name ,  GVariant  *  parameters ,  const   GVariantType  *  reply_type ,  GDBusCallFlags   flags ,  gint   timeout_msec ,  GUnixFDList  *  fd_list ,  GCancellable  *  cancellable ,  GAsyncReadyCallback   callback ,  gpointer   user_data );
extern   GVariant  *  g_dbus_connection_call_with_unix_fd_list_finish ( GDBusConnection  *  connection ,  GUnixFDList  * *  out_fd_list ,  GAsyncResult  *  res ,  GError  * *  error );
extern   GVariant  *  g_dbus_connection_call_with_unix_fd_list_sync ( GDBusConnection  *  connection ,  const   gchar  *  bus_name ,  const   gchar  *  object_path ,  const   gchar  *  interface_name ,  const   gchar  *  method_name ,  GVariant  *  parameters ,  const   GVariantType  *  reply_type ,  GDBusCallFlags   flags ,  gint   timeout_msec ,  GUnixFDList  *  fd_list ,  GUnixFDList  * *  out_fd_list ,  GCancellable  *  cancellable ,  GError  * *  error );
extern   guint   g_dbus_connection_register_object ( GDBusConnection  *  connection ,  const   gchar  *  object_path ,  GDBusInterfaceInfo  *  interface_info ,  const   GDBusInterfaceVTable  *  vtable ,  gpointer   user_data ,  GDestroyNotify   user_data_free_func ,  GError  * *  error );
extern   guint   g_dbus_connection_register_object_with_closures ( GDBusConnection  *  connection ,  const   gchar  *  object_path ,  GDBusInterfaceInfo  *  interface_info ,  GClosure  *  method_call_closure ,  GClosure  *  get_property_closure ,  GClosure  *  set_property_closure ,  GError  * *  error );
extern   gboolean   g_dbus_connection_unregister_object ( GDBusConnection  *  connection ,  guint   registration_id );
extern   guint   g_dbus_connection_register_subtree ( GDBusConnection  *  connection ,  const   gchar  *  object_path ,  const   GDBusSubtreeVTable  *  vtable ,  GDBusSubtreeFlags   flags ,  gpointer   user_data ,  GDestroyNotify   user_data_free_func ,  GError  * *  error );
extern   gboolean   g_dbus_connection_unregister_subtree ( GDBusConnection  *  connection ,  guint   registration_id );
extern   guint   g_dbus_connection_signal_subscribe ( GDBusConnection  *  connection ,  const   gchar  *  sender ,  const   gchar  *  interface_name ,  const   gchar  *  member ,  const   gchar  *  object_path ,  const   gchar  *  arg0 ,  GDBusSignalFlags   flags ,  GDBusSignalCallback   callback ,  gpointer   user_data ,  GDestroyNotify   user_data_free_func );
extern   void   g_dbus_connection_signal_unsubscribe ( GDBusConnection  *  connection ,  guint   subscription_id );
extern   guint   g_dbus_connection_add_filter ( GDBusConnection  *  connection ,  GDBusMessageFilterFunction   filter_function ,  gpointer   user_data ,  GDestroyNotify   user_data_free_func );
extern   void   g_dbus_connection_remove_filter ( GDBusConnection  *  connection ,  guint   filter_id );
extern   GQuark   g_dbus_error_quark ();
extern   gboolean   g_dbus_error_is_remote_error ( const   GError  *  error );
extern   gchar  *  g_dbus_error_get_remote_error ( const   GError  *  error );
extern   gboolean   g_dbus_error_strip_remote_error ( GError  *  error );
extern   gboolean   g_dbus_error_register_error ( GQuark   error_domain ,  gint   error_code ,  const   gchar  *  dbus_error_name );
extern   gboolean   g_dbus_error_unregister_error ( GQuark   error_domain ,  gint   error_code ,  const   gchar  *  dbus_error_name );
extern   void   g_dbus_error_register_error_domain ( const   gchar  *  error_domain_quark_name ,  volatile   gsize  *  quark_volatile ,  const   GDBusErrorEntry  *  entries ,  guint   num_entries );
extern   GError  *  g_dbus_error_new_for_dbus_error ( const   gchar  *  dbus_error_name ,  const   gchar  *  dbus_error_message );
extern   void   g_dbus_error_set_dbus_error ( GError  * *  error ,  const   gchar  *  dbus_error_name ,  const   gchar  *  dbus_error_message ,  const   gchar  *  format , ...);
extern   void   g_dbus_error_set_dbus_error_valist ( GError  * *  error ,  const   gchar  *  dbus_error_name ,  const   gchar  *  dbus_error_message ,  const   gchar  *  format ,  va_list   var_args );
extern   gchar  *  g_dbus_error_encode_gerror ( const   GError  *  error );
extern   GType   g_dbus_interface_get_type ();
extern   GDBusInterfaceInfo  *  g_dbus_interface_get_info ( GDBusInterface  *  interface_ );
extern   GDBusObject  *  g_dbus_interface_get_object ( GDBusInterface  *  interface_ );
extern   void   g_dbus_interface_set_object ( GDBusInterface  *  interface_ ,  GDBusObject  *  object );
extern   GDBusObject  *  g_dbus_interface_dup_object ( GDBusInterface  *  interface_ );
extern   GType   g_dbus_interface_skeleton_get_type ();
extern   GDBusInterfaceSkeletonFlags   g_dbus_interface_skeleton_get_flags ( GDBusInterfaceSkeleton  *  interface_ );
extern   void   g_dbus_interface_skeleton_set_flags ( GDBusInterfaceSkeleton  *  interface_ ,  GDBusInterfaceSkeletonFlags   flags );
extern   GDBusInterfaceInfo  *  g_dbus_interface_skeleton_get_info ( GDBusInterfaceSkeleton  *  interface_ );
extern   GDBusInterfaceVTable  *  g_dbus_interface_skeleton_get_vtable ( GDBusInterfaceSkeleton  *  interface_ );
extern   GVariant  *  g_dbus_interface_skeleton_get_properties ( GDBusInterfaceSkeleton  *  interface_ );
extern   void   g_dbus_interface_skeleton_flush ( GDBusInterfaceSkeleton  *  interface_ );
extern   gboolean   g_dbus_interface_skeleton_export ( GDBusInterfaceSkeleton  *  interface_ ,  GDBusConnection  *  connection ,  const   gchar  *  object_path ,  GError  * *  error );
extern   void   g_dbus_interface_skeleton_unexport ( GDBusInterfaceSkeleton  *  interface_ );
extern   void   g_dbus_interface_skeleton_unexport_from_connection ( GDBusInterfaceSkeleton  *  interface_ ,  GDBusConnection  *  connection );
extern   GDBusConnection  *  g_dbus_interface_skeleton_get_connection ( GDBusInterfaceSkeleton  *  interface_ );
extern   GList  *  g_dbus_interface_skeleton_get_connections ( GDBusInterfaceSkeleton  *  interface_ );
extern   gboolean   g_dbus_interface_skeleton_has_connection ( GDBusInterfaceSkeleton  *  interface_ ,  GDBusConnection  *  connection );
extern   const   gchar  *  g_dbus_interface_skeleton_get_object_path ( GDBusInterfaceSkeleton  *  interface_ );
extern   const   gchar  *  g_dbus_annotation_info_lookup ( GDBusAnnotationInfo  * *  annotations ,  const   gchar  *  name );
extern   GDBusMethodInfo  *  g_dbus_interface_info_lookup_method ( GDBusInterfaceInfo  *  info ,  const   gchar  *  name );
extern   GDBusSignalInfo  *  g_dbus_interface_info_lookup_signal ( GDBusInterfaceInfo  *  info ,  const   gchar  *  name );
extern   GDBusPropertyInfo  *  g_dbus_interface_info_lookup_property ( GDBusInterfaceInfo  *  info ,  const   gchar  *  name );
extern   void   g_dbus_interface_info_cache_build ( GDBusInterfaceInfo  *  info );
extern   void   g_dbus_interface_info_cache_release ( GDBusInterfaceInfo  *  info );
extern   void   g_dbus_interface_info_generate_xml ( GDBusInterfaceInfo  *  info ,  guint   indent ,  GString  *  string_builder );
extern   GDBusNodeInfo  *  g_dbus_node_info_new_for_xml ( const   gchar  *  xml_data ,  GError  * *  error );
extern   GDBusInterfaceInfo  *  g_dbus_node_info_lookup_interface ( GDBusNodeInfo  *  info ,  const   gchar  *  name );
extern   void   g_dbus_node_info_generate_xml ( GDBusNodeInfo  *  info ,  guint   indent ,  GString  *  string_builder );
extern   GDBusNodeInfo  *  g_dbus_node_info_ref ( GDBusNodeInfo  *  info );
extern   GDBusInterfaceInfo  *  g_dbus_interface_info_ref ( GDBusInterfaceInfo  *  info );
extern   GDBusMethodInfo  *  g_dbus_method_info_ref ( GDBusMethodInfo  *  info );
extern   GDBusSignalInfo  *  g_dbus_signal_info_ref ( GDBusSignalInfo  *  info );
extern   GDBusPropertyInfo  *  g_dbus_property_info_ref ( GDBusPropertyInfo  *  info );
extern   GDBusArgInfo  *  g_dbus_arg_info_ref ( GDBusArgInfo  *  info );
extern   GDBusAnnotationInfo  *  g_dbus_annotation_info_ref ( GDBusAnnotationInfo  *  info );
extern   void   g_dbus_node_info_unref ( GDBusNodeInfo  *  info );
extern   void   g_dbus_interface_info_unref ( GDBusInterfaceInfo  *  info );
extern   void   g_dbus_method_info_unref ( GDBusMethodInfo  *  info );
extern   void   g_dbus_signal_info_unref ( GDBusSignalInfo  *  info );
extern   void   g_dbus_property_info_unref ( GDBusPropertyInfo  *  info );
extern   void   g_dbus_arg_info_unref ( GDBusArgInfo  *  info );
extern   void   g_dbus_annotation_info_unref ( GDBusAnnotationInfo  *  info );
extern   GType   g_dbus_node_info_get_type ();
extern   GType   g_dbus_interface_info_get_type ();
extern   GType   g_dbus_method_info_get_type ();
extern   GType   g_dbus_signal_info_get_type ();
extern   GType   g_dbus_property_info_get_type ();
extern   GType   g_dbus_arg_info_get_type ();
extern   GType   g_dbus_annotation_info_get_type ();
extern   GType   g_dbus_menu_model_get_type ();
extern   GDBusMenuModel  *  g_dbus_menu_model_get ( GDBusConnection  *  connection ,  const   gchar  *  bus_name ,  const   gchar  *  object_path );
extern   GType   g_dbus_message_get_type ();
extern   GDBusMessage  *  g_dbus_message_new ();
extern   GDBusMessage  *  g_dbus_message_new_signal ( const   gchar  *  path ,  const   gchar  *  interface_ ,  const   gchar  *  signal );
extern   GDBusMessage  *  g_dbus_message_new_method_call ( const   gchar  *  name ,  const   gchar  *  path ,  const   gchar  *  interface_ ,  const   gchar  *  method );
extern   GDBusMessage  *  g_dbus_message_new_method_reply ( GDBusMessage  *  method_call_message );
extern   GDBusMessage  *  g_dbus_message_new_method_error ( GDBusMessage  *  method_call_message ,  const   gchar  *  error_name ,  const   gchar  *  error_message_format , ...);
extern   GDBusMessage  *  g_dbus_message_new_method_error_valist ( GDBusMessage  *  method_call_message ,  const   gchar  *  error_name ,  const   gchar  *  error_message_format ,  va_list   var_args );
extern   GDBusMessage  *  g_dbus_message_new_method_error_literal ( GDBusMessage  *  method_call_message ,  const   gchar  *  error_name ,  const   gchar  *  error_message );
extern   gchar  *  g_dbus_message_print ( GDBusMessage  *  message ,  guint   indent );
extern   gboolean   g_dbus_message_get_locked ( GDBusMessage  *  message );
extern   void   g_dbus_message_lock ( GDBusMessage  *  message );
extern   GDBusMessage  *  g_dbus_message_copy ( GDBusMessage  *  message ,  GError  * *  error );
extern   GDBusMessageByteOrder   g_dbus_message_get_byte_order ( GDBusMessage  *  message );
extern   void   g_dbus_message_set_byte_order ( GDBusMessage  *  message ,  GDBusMessageByteOrder   byte_order );
extern   GDBusMessageType   g_dbus_message_get_message_type ( GDBusMessage  *  message );
extern   void   g_dbus_message_set_message_type ( GDBusMessage  *  message ,  GDBusMessageType   type );
extern   GDBusMessageFlags   g_dbus_message_get_flags ( GDBusMessage  *  message );
extern   void   g_dbus_message_set_flags ( GDBusMessage  *  message ,  GDBusMessageFlags   flags );
extern   guint32   g_dbus_message_get_serial ( GDBusMessage  *  message );
extern   void   g_dbus_message_set_serial ( GDBusMessage  *  message ,  guint32   serial );
extern   GVariant  *  g_dbus_message_get_header ( GDBusMessage  *  message ,  GDBusMessageHeaderField   header_field );
extern   void   g_dbus_message_set_header ( GDBusMessage  *  message ,  GDBusMessageHeaderField   header_field ,  GVariant  *  value );
extern   guchar  *  g_dbus_message_get_header_fields ( GDBusMessage  *  message );
extern   GVariant  *  g_dbus_message_get_body ( GDBusMessage  *  message );
extern   void   g_dbus_message_set_body ( GDBusMessage  *  message ,  GVariant  *  body );
extern   GUnixFDList  *  g_dbus_message_get_unix_fd_list ( GDBusMessage  *  message );
extern   void   g_dbus_message_set_unix_fd_list ( GDBusMessage  *  message ,  GUnixFDList  *  fd_list );
extern   guint32   g_dbus_message_get_reply_serial ( GDBusMessage  *  message );
extern   void   g_dbus_message_set_reply_serial ( GDBusMessage  *  message ,  guint32   value );
extern   const   gchar  *  g_dbus_message_get_interface ( GDBusMessage  *  message );
extern   void   g_dbus_message_set_interface ( GDBusMessage  *  message ,  const   gchar  *  value );
extern   const   gchar  *  g_dbus_message_get_member ( GDBusMessage  *  message );
extern   void   g_dbus_message_set_member ( GDBusMessage  *  message ,  const   gchar  *  value );
extern   const   gchar  *  g_dbus_message_get_path ( GDBusMessage  *  message );
extern   void   g_dbus_message_set_path ( GDBusMessage  *  message ,  const   gchar  *  value );
extern   const   gchar  *  g_dbus_message_get_sender ( GDBusMessage  *  message );
extern   void   g_dbus_message_set_sender ( GDBusMessage  *  message ,  const   gchar  *  value );
extern   const   gchar  *  g_dbus_message_get_destination ( GDBusMessage  *  message );
extern   void   g_dbus_message_set_destination ( GDBusMessage  *  message ,  const   gchar  *  value );
extern   const   gchar  *  g_dbus_message_get_error_name ( GDBusMessage  *  message );
extern   void   g_dbus_message_set_error_name ( GDBusMessage  *  message ,  const   gchar  *  value );
extern   const   gchar  *  g_dbus_message_get_signature ( GDBusMessage  *  message );
extern   void   g_dbus_message_set_signature ( GDBusMessage  *  message ,  const   gchar  *  value );
extern   guint32   g_dbus_message_get_num_unix_fds ( GDBusMessage  *  message );
extern   void   g_dbus_message_set_num_unix_fds ( GDBusMessage  *  message ,  guint32   value );
extern   const   gchar  *  g_dbus_message_get_arg0 ( GDBusMessage  *  message );
extern   const   gchar  *  g_dbus_message_get_arg0_path ( GDBusMessage  *  message );
extern   GDBusMessage  *  g_dbus_message_new_from_blob ( guchar  *  blob ,  gsize   blob_len ,  GDBusCapabilityFlags   capabilities ,  GError  * *  error );
extern   gssize   g_dbus_message_bytes_needed ( guchar  *  blob ,  gsize   blob_len ,  GError  * *  error );
extern   guchar  *  g_dbus_message_to_blob ( GDBusMessage  *  message ,  gsize  *  out_size ,  GDBusCapabilityFlags   capabilities ,  GError  * *  error );
extern   gboolean   g_dbus_message_to_gerror ( GDBusMessage  *  message ,  GError  * *  error );
extern   GType   g_dbus_method_invocation_get_type ();
extern   const   gchar  *  g_dbus_method_invocation_get_sender ( GDBusMethodInvocation  *  invocation );
extern   const   gchar  *  g_dbus_method_invocation_get_object_path ( GDBusMethodInvocation  *  invocation );
extern   const   gchar  *  g_dbus_method_invocation_get_interface_name ( GDBusMethodInvocation  *  invocation );
extern   const   gchar  *  g_dbus_method_invocation_get_method_name ( GDBusMethodInvocation  *  invocation );
extern   const   GDBusMethodInfo  *  g_dbus_method_invocation_get_method_info ( GDBusMethodInvocation  *  invocation );
extern   const   GDBusPropertyInfo  *  g_dbus_method_invocation_get_property_info ( GDBusMethodInvocation  *  invocation );
extern   GDBusConnection  *  g_dbus_method_invocation_get_connection ( GDBusMethodInvocation  *  invocation );
extern   GDBusMessage  *  g_dbus_method_invocation_get_message ( GDBusMethodInvocation  *  invocation );
extern   GVariant  *  g_dbus_method_invocation_get_parameters ( GDBusMethodInvocation  *  invocation );
extern   gpointer   g_dbus_method_invocation_get_user_data ( GDBusMethodInvocation  *  invocation );
extern   void   g_dbus_method_invocation_return_value ( GDBusMethodInvocation  *  invocation ,  GVariant  *  parameters );
extern   void   g_dbus_method_invocation_return_value_with_unix_fd_list ( GDBusMethodInvocation  *  invocation ,  GVariant  *  parameters ,  GUnixFDList  *  fd_list );
extern   void   g_dbus_method_invocation_return_error ( GDBusMethodInvocation  *  invocation ,  GQuark   domain ,  gint   code ,  const   gchar  *  format , ...);
extern   void   g_dbus_method_invocation_return_error_valist ( GDBusMethodInvocation  *  invocation ,  GQuark   domain ,  gint   code ,  const   gchar  *  format ,  va_list   var_args );
extern   void   g_dbus_method_invocation_return_error_literal ( GDBusMethodInvocation  *  invocation ,  GQuark   domain ,  gint   code ,  const   gchar  *  message );
extern   void   g_dbus_method_invocation_return_gerror ( GDBusMethodInvocation  *  invocation ,  const   GError  *  error );
extern   void   g_dbus_method_invocation_take_error ( GDBusMethodInvocation  *  invocation ,  GError  *  error );
extern   void   g_dbus_method_invocation_return_dbus_error ( GDBusMethodInvocation  *  invocation ,  const   gchar  *  error_name ,  const   gchar  *  error_message );
extern   GType   g_dbus_object_get_type ();
extern   const   gchar  *  g_dbus_object_get_object_path ( GDBusObject  *  object );
extern   GList  *  g_dbus_object_get_interfaces ( GDBusObject  *  object );
extern   GDBusInterface  *  g_dbus_object_get_interface ( GDBusObject  *  object ,  const   gchar  *  interface_name );
extern   GType   g_dbus_object_manager_get_type ();
extern   const   gchar  *  g_dbus_object_manager_get_object_path ( GDBusObjectManager  *  manager );
extern   GList  *  g_dbus_object_manager_get_objects ( GDBusObjectManager  *  manager );
extern   GDBusObject  *  g_dbus_object_manager_get_object ( GDBusObjectManager  *  manager ,  const   gchar  *  object_path );
extern   GDBusInterface  *  g_dbus_object_manager_get_interface ( GDBusObjectManager  *  manager ,  const   gchar  *  object_path ,  const   gchar  *  interface_name );
extern   GType   g_dbus_object_manager_client_get_type ();
extern   void   g_dbus_object_manager_client_new ( GDBusConnection  *  connection ,  GDBusObjectManagerClientFlags   flags ,  const   gchar  *  name ,  const   gchar  *  object_path ,  GDBusProxyTypeFunc   get_proxy_type_func ,  gpointer   get_proxy_type_user_data ,  GDestroyNotify   get_proxy_type_destroy_notify ,  GCancellable  *  cancellable ,  GAsyncReadyCallback   callback ,  gpointer   user_data );
extern   GDBusObjectManager  *  g_dbus_object_manager_client_new_finish ( GAsyncResult  *  res ,  GError  * *  error );
extern   GDBusObjectManager  *  g_dbus_object_manager_client_new_sync ( GDBusConnection  *  connection ,  GDBusObjectManagerClientFlags   flags ,  const   gchar  *  name ,  const   gchar  *  object_path ,  GDBusProxyTypeFunc   get_proxy_type_func ,  gpointer   get_proxy_type_user_data ,  GDestroyNotify   get_proxy_type_destroy_notify ,  GCancellable  *  cancellable ,  GError  * *  error );
extern   void   g_dbus_object_manager_client_new_for_bus ( GBusType   bus_type ,  GDBusObjectManagerClientFlags   flags ,  const   gchar  *  name ,  const   gchar  *  object_path ,  GDBusProxyTypeFunc   get_proxy_type_func ,  gpointer   get_proxy_type_user_data ,  GDestroyNotify   get_proxy_type_destroy_notify ,  GCancellable  *  cancellable ,  GAsyncReadyCallback   callback ,  gpointer   user_data );
extern   GDBusObjectManager  *  g_dbus_object_manager_client_new_for_bus_finish ( GAsyncResult  *  res ,  GError  * *  error );
extern   GDBusObjectManager  *  g_dbus_object_manager_client_new_for_bus_sync ( GBusType   bus_type ,  GDBusObjectManagerClientFlags   flags ,  const   gchar  *  name ,  const   gchar  *  object_path ,  GDBusProxyTypeFunc   get_proxy_type_func ,  gpointer   get_proxy_type_user_data ,  GDestroyNotify   get_proxy_type_destroy_notify ,  GCancellable  *  cancellable ,  GError  * *  error );
extern   GDBusConnection  *  g_dbus_object_manager_client_get_connection ( GDBusObjectManagerClient  *  manager );
extern   GDBusObjectManagerClientFlags   g_dbus_object_manager_client_get_flags ( GDBusObjectManagerClient  *  manager );
extern   const   gchar  *  g_dbus_object_manager_client_get_name ( GDBusObjectManagerClient  *  manager );
extern   gchar  *  g_dbus_object_manager_client_get_name_owner ( GDBusObjectManagerClient  *  manager );
extern   GType   g_dbus_object_manager_server_get_type ();
extern   GDBusObjectManagerServer  *  g_dbus_object_manager_server_new ( const   gchar  *  object_path );
extern   GDBusConnection  *  g_dbus_object_manager_server_get_connection ( GDBusObjectManagerServer  *  manager );
extern   void   g_dbus_object_manager_server_set_connection ( GDBusObjectManagerServer  *  manager ,  GDBusConnection  *  connection );
extern   void   g_dbus_object_manager_server_export ( GDBusObjectManagerServer  *  manager ,  GDBusObjectSkeleton  *  object );
extern   void   g_dbus_object_manager_server_export_uniquely ( GDBusObjectManagerServer  *  manager ,  GDBusObjectSkeleton  *  object );
extern   gboolean   g_dbus_object_manager_server_is_exported ( GDBusObjectManagerServer  *  manager ,  GDBusObjectSkeleton  *  object );
extern   gboolean   g_dbus_object_manager_server_unexport ( GDBusObjectManagerServer  *  manager ,  const   gchar  *  object_path );
extern   GType   g_dbus_object_proxy_get_type ();
extern   GDBusObjectProxy  *  g_dbus_object_proxy_new ( GDBusConnection  *  connection ,  const   gchar  *  object_path );
extern   GDBusConnection  *  g_dbus_object_proxy_get_connection ( GDBusObjectProxy  *  proxy );
extern   GType   g_dbus_object_skeleton_get_type ();
extern   GDBusObjectSkeleton  *  g_dbus_object_skeleton_new ( const   gchar  *  object_path );
extern   void   g_dbus_object_skeleton_flush ( GDBusObjectSkeleton  *  object );
extern   void   g_dbus_object_skeleton_add_interface ( GDBusObjectSkeleton  *  object ,  GDBusInterfaceSkeleton  *  interface_ );
extern   void   g_dbus_object_skeleton_remove_interface ( GDBusObjectSkeleton  *  object ,  GDBusInterfaceSkeleton  *  interface_ );
extern   void   g_dbus_object_skeleton_remove_interface_by_name ( GDBusObjectSkeleton  *  object ,  const   gchar  *  interface_name );
extern   void   g_dbus_object_skeleton_set_object_path ( GDBusObjectSkeleton  *  object ,  const   gchar  *  object_path );
extern   GType   g_dbus_proxy_get_type ();
extern   void   g_dbus_proxy_new ( GDBusConnection  *  connection ,  GDBusProxyFlags   flags ,  GDBusInterfaceInfo  *  info ,  const   gchar  *  name ,  const   gchar  *  object_path ,  const   gchar  *  interface_name ,  GCancellable  *  cancellable ,  GAsyncReadyCallback   callback ,  gpointer   user_data );
extern   GDBusProxy  *  g_dbus_proxy_new_finish ( GAsyncResult  *  res ,  GError  * *  error );
extern   GDBusProxy  *  g_dbus_proxy_new_sync ( GDBusConnection  *  connection ,  GDBusProxyFlags   flags ,  GDBusInterfaceInfo  *  info ,  const   gchar  *  name ,  const   gchar  *  object_path ,  const   gchar  *  interface_name ,  GCancellable  *  cancellable ,  GError  * *  error );
extern   void   g_dbus_proxy_new_for_bus ( GBusType   bus_type ,  GDBusProxyFlags   flags ,  GDBusInterfaceInfo  *  info ,  const   gchar  *  name ,  const   gchar  *  object_path ,  const   gchar  *  interface_name ,  GCancellable  *  cancellable ,  GAsyncReadyCallback   callback ,  gpointer   user_data );
extern   GDBusProxy  *  g_dbus_proxy_new_for_bus_finish ( GAsyncResult  *  res ,  GError  * *  error );
extern   GDBusProxy  *  g_dbus_proxy_new_for_bus_sync ( GBusType   bus_type ,  GDBusProxyFlags   flags ,  GDBusInterfaceInfo  *  info ,  const   gchar  *  name ,  const   gchar  *  object_path ,  const   gchar  *  interface_name ,  GCancellable  *  cancellable ,  GError  * *  error );
extern   GDBusConnection  *  g_dbus_proxy_get_connection ( GDBusProxy  *  proxy );
extern   GDBusProxyFlags   g_dbus_proxy_get_flags ( GDBusProxy  *  proxy );
extern   const   gchar  *  g_dbus_proxy_get_name ( GDBusProxy  *  proxy );
extern   gchar  *  g_dbus_proxy_get_name_owner ( GDBusProxy  *  proxy );
extern   const   gchar  *  g_dbus_proxy_get_object_path ( GDBusProxy  *  proxy );
extern   const   gchar  *  g_dbus_proxy_get_interface_name ( GDBusProxy  *  proxy );
extern   gint   g_dbus_proxy_get_default_timeout ( GDBusProxy  *  proxy );
extern   void   g_dbus_proxy_set_default_timeout ( GDBusProxy  *  proxy ,  gint   timeout_msec );
extern   GDBusInterfaceInfo  *  g_dbus_proxy_get_interface_info ( GDBusProxy  *  proxy );
extern   void   g_dbus_proxy_set_interface_info ( GDBusProxy  *  proxy ,  GDBusInterfaceInfo  *  info );
extern   GVariant  *  g_dbus_proxy_get_cached_property ( GDBusProxy  *  proxy ,  const   gchar  *  property_name );
extern   void   g_dbus_proxy_set_cached_property ( GDBusProxy  *  proxy ,  const   gchar  *  property_name ,  GVariant  *  value );
extern   gchar  * *  g_dbus_proxy_get_cached_property_names ( GDBusProxy  *  proxy );
extern   void   g_dbus_proxy_call ( GDBusProxy  *  proxy ,  const   gchar  *  method_name ,  GVariant  *  parameters ,  GDBusCallFlags   flags ,  gint   timeout_msec ,  GCancellable  *  cancellable ,  GAsyncReadyCallback   callback ,  gpointer   user_data );
extern   GVariant  *  g_dbus_proxy_call_finish ( GDBusProxy  *  proxy ,  GAsyncResult  *  res ,  GError  * *  error );
extern   GVariant  *  g_dbus_proxy_call_sync ( GDBusProxy  *  proxy ,  const   gchar  *  method_name ,  GVariant  *  parameters ,  GDBusCallFlags   flags ,  gint   timeout_msec ,  GCancellable  *  cancellable ,  GError  * *  error );
extern   void   g_dbus_proxy_call_with_unix_fd_list ( GDBusProxy  *  proxy ,  const   gchar  *  method_name ,  GVariant  *  parameters ,  GDBusCallFlags   flags ,  gint   timeout_msec ,  GUnixFDList  *  fd_list ,  GCancellable  *  cancellable ,  GAsyncReadyCallback   callback ,  gpointer   user_data );
extern   GVariant  *  g_dbus_proxy_call_with_unix_fd_list_finish ( GDBusProxy  *  proxy ,  GUnixFDList  * *  out_fd_list ,  GAsyncResult  *  res ,  GError  * *  error );
extern   GVariant  *  g_dbus_proxy_call_with_unix_fd_list_sync ( GDBusProxy  *  proxy ,  const   gchar  *  method_name ,  GVariant  *  parameters ,  GDBusCallFlags   flags ,  gint   timeout_msec ,  GUnixFDList  *  fd_list ,  GUnixFDList  * *  out_fd_list ,  GCancellable  *  cancellable ,  GError  * *  error );
extern   GType   g_dbus_server_get_type ();
extern   GDBusServer  *  g_dbus_server_new_sync ( const   gchar  *  address ,  GDBusServerFlags   flags ,  const   gchar  *  guid ,  GDBusAuthObserver  *  observer ,  GCancellable  *  cancellable ,  GError  * *  error );
extern   const   gchar  *  g_dbus_server_get_client_address ( GDBusServer  *  server );
extern   const   gchar  *  g_dbus_server_get_guid ( GDBusServer  *  server );
extern   GDBusServerFlags   g_dbus_server_get_flags ( GDBusServer  *  server );
extern   void   g_dbus_server_start ( GDBusServer  *  server );
extern   void   g_dbus_server_stop ( GDBusServer  *  server );
extern   gboolean   g_dbus_server_is_active ( GDBusServer  *  server );
extern   gboolean   g_dbus_is_guid ( const   gchar  *  string );
extern   gchar  *  g_dbus_generate_guid ();
extern   gboolean   g_dbus_is_name ( const   gchar  *  string );
extern   gboolean   g_dbus_is_unique_name ( const   gchar  *  string );
extern   gboolean   g_dbus_is_member_name ( const   gchar  *  string );
extern   gboolean   g_dbus_is_interface_name ( const   gchar  *  string );
extern   gboolean   g_dbus_is_error_name ( const   gchar  *  string );
extern   void   g_dbus_gvariant_to_gvalue ( GVariant  *  value ,  GValue  *  out_gvalue );
extern   GVariant  *  g_dbus_gvalue_to_gvariant ( const   GValue  *  gvalue ,  const   GVariantType  *  type );
extern   gchar  *  g_dbus_escape_object_path_bytestring ( const   guint8  *  bytes );
extern   gchar  *  g_dbus_escape_object_path ( const   gchar  *  s );
extern   guint8  *  g_dbus_unescape_object_path ( const   gchar  *  s );
extern   GType   g_dbus_proxy_flags_get_type ();
extern   GType   g_dbus_error_get_type ();
extern   GType   g_dbus_connection_flags_get_type ();
extern   GType   g_dbus_capability_flags_get_type ();
extern   GType   g_dbus_call_flags_get_type ();
extern   GType   g_dbus_message_type_get_type ();
extern   GType   g_dbus_message_flags_get_type ();
extern   GType   g_dbus_message_header_field_get_type ();
extern   GType   g_dbus_property_info_flags_get_type ();
extern   GType   g_dbus_subtree_flags_get_type ();
extern   GType   g_dbus_server_flags_get_type ();
extern   GType   g_dbus_signal_flags_get_type ();
extern   GType   g_dbus_send_message_flags_get_type ();
extern   GType   g_dbus_message_byte_order_get_type ();
extern   GType   g_dbus_interface_skeleton_flags_get_type ();
extern   GType   g_dbus_object_manager_client_flags_get_type ();
extern   guint   g_dbus_connection_export_menu_model ( GDBusConnection  *  connection ,  const   gchar  *  object_path ,  GMenuModel  *  menu ,  GError  * *  error );
extern   void   g_dbus_connection_unexport_menu_model ( GDBusConnection  *  connection ,  guint   export_id );
